+Fix detailsLoading does not exist...
[INFO] ERROR in src/main/webapp/app/risk-management/risk-details/risk-details.component.html(1,124): : Property 'detailsLoading' does not exist on type 'RiskDetailsComponent'.